CREATE OR REPLACE PACKAGE PKG_TEACHER AS
    SUBTYPE T_ID IS TEACHERS.TEACHER_ID%TYPE;

    FUNCTION NEW(p_user_id PKG_USER.T_ID) RETURN T_ID;

    FUNCTION IS_TEACHER(p_user_id PKG_USER.T_ID) RETURN BOOLEAN;

    FUNCTION GET_ALL RETURN SYS_REFCURSOR;

    FUNCTION GET_BY_ID(p_teacher_id T_ID) RETURN SYS_REFCURSOR;

    FUNCTION GET_BY_USER(p_user_id PKG_USER.T_ID) RETURN SYS_REFCURSOR;
END;

CREATE OR REPLACE PACKAGE BODY PKG_TEACHER AS
    FUNCTION NEW(p_user_id PKG_USER.T_ID) RETURN T_ID AS
        v_id T_ID;
    BEGIN
        INSERT INTO TEACHERS(USER_ID) VALUES (p_user_id) RETURNING TEACHER_ID INTO v_id;
        COMMIT;
        RETURN v_id;
    END;

    FUNCTION IS_TEACHER(p_user_id PKG_USER.T_ID) RETURN BOOLEAN AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM TEACHERS WHERE USER_ID = p_user_id;
        RETURN (v_count = 1);
    END;

    FUNCTION GET_ALL RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_TEACHERS;
        RETURN v_cursor;
    END;

    FUNCTION GET_BY_ID(p_teacher_id T_ID) RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_TEACHERS WHERE TEACHER_ID = p_teacher_id;
        RETURN v_cursor;
    END;

    FUNCTION GET_BY_USER(p_user_id PKG_USER.T_ID) RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_TEACHERS WHERE USER_ID = p_user_id;
        RETURN v_cursor;
    END;
END;