CREATE OR REPLACE PACKAGE PKG_CLASSROOM AS
    SUBTYPE T_ID IS CLASSROOMS.CLASSROOM_ID%TYPE;
    SUBTYPE T_NAME IS CLASSROOMS.NAME%TYPE;
    SUBTYPE T_CAPACITY IS CLASSROOMS.CAPACITY%TYPE;

    FUNCTION NEW(p_name T_NAME, p_capacity T_CAPACITY) RETURN T_ID;

    FUNCTION GET_ALL RETURN SYS_REFCURSOR;

    FUNCTION GET_BY_ID(p_classroom_id T_ID) RETURN SYS_REFCURSOR;

    FUNCTION GET_BY_CAPACITY(p_capacity T_CAPACITY) RETURN SYS_REFCURSOR;

    PROCEDURE UPDATE_NAME(p_classroom_id T_ID, p_name T_NAME);

    PROCEDURE UPDATE_CAPACITY(p_classroom_id T_ID, p_capacity T_CAPACITY);

    PROCEDURE REMOVE(p_classroom_id T_ID);
END;

CREATE OR REPLACE PACKAGE BODY PKG_CLASSROOM AS
    FUNCTION NEW(p_name T_NAME, p_capacity T_CAPACITY) RETURN T_ID AS
        v_id T_ID;
    BEGIN
        INSERT INTO CLASSROOMS(NAME, CAPACITY) VALUES (p_name, p_capacity) RETURNING CLASSROOM_ID INTO v_id;
        COMMIT;
        RETURN v_id;
    END;

    FUNCTION GET_ALL RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_CLASSROOMS;
        RETURN v_cursor;
    END;

    FUNCTION GET_BY_ID(p_classroom_id T_ID) RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_CLASSROOMS WHERE CLASSROOM_ID = p_classroom_id;
        RETURN v_cursor;
    END;

    FUNCTION GET_BY_CAPACITY(p_capacity T_CAPACITY) RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_CLASSROOMS WHERE CAPACITY >= p_capacity ORDER BY CAPACITY;
        RETURN v_cursor;
    END;

    PROCEDURE UPDATE_NAME(p_classroom_id T_ID, p_name T_NAME) AS
    BEGIN
        UPDATE CLASSROOMS SET NAME = p_name WHERE CLASSROOM_ID = p_classroom_id;
        COMMIT;
    END;

    PROCEDURE UPDATE_CAPACITY(p_classroom_id T_ID, p_capacity T_CAPACITY) AS
    BEGIN
        UPDATE CLASSROOMS SET CAPACITY = p_capacity WHERE CLASSROOM_ID = p_classroom_id;
        COMMIT;
    END;

    PROCEDURE REMOVE(p_classroom_id T_ID) AS
    BEGIN
        DELETE FROM CLASSROOMS WHERE CLASSROOM_ID = p_classroom_id;
    END;
END;