CREATE OR REPLACE PACKAGE PKG_USERS_STATUS AS
    SUBTYPE T_ID IS USERS_STATUS.STATUS_ID%TYPE;

    FUNCTION GET_ALL RETURN SYS_REFCURSOR;

    FUNCTION GET_BY_ID(p_status_id T_ID) RETURN SYS_REFCURSOR;
END;

CREATE OR REPLACE PACKAGE BODY PKG_USERS_STATUS AS
    FUNCTION GET_ALL RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_USERS_STATUS;
        RETURN v_cursor;
    END;

    FUNCTION GET_BY_ID(p_status_id T_ID) RETURN SYS_REFCURSOR AS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR SELECT * FROM VW_USERS_STATUS WHERE STATUS_ID = p_status_id;
        RETURN v_cursor;
    END;
END;